services:
  - type: web
    name: inimigos-do-prompt-api
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: MODEL_BACKEND
        value: "gradio_space"
      - key: SUPABASE_JWT_SECRET
        sync: false
