FROM python:3.12-slim

WORKDIR /app

COPY requirements-api.txt .

RUN pip install --no-cache-dir -r requirements-api.txt celery redis beautifulsoup4

COPY . .

CMD ["celery", "-A", "app.worker", "worker", "--beat", "--loglevel=info"]
